-- ==========================================================================
-- MVP Bot de triage + avisos globales administrables
-- ==========================================================================

CREATE TABLE IF NOT EXISTS public.bot_incidents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope TEXT NOT NULL DEFAULT 'global' CHECK (scope IN ('global')),
  service TEXT NOT NULL CHECK (service IN ('internet', 'wifi', 'telefonia', 'sistema', 'otro')),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'resolved')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ,
  resolution_note TEXT,
  created_by UUID REFERENCES public.profiles(id),
  resolved_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bot_incidents_status_started_at
  ON public.bot_incidents(status, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_bot_incidents_service
  ON public.bot_incidents(service);

CREATE TABLE IF NOT EXISTS public.bot_triage_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id),
  question TEXT NOT NULL,
  normalized_topic TEXT,
  bot_response TEXT NOT NULL,
  incident_id BIGINT REFERENCES public.bot_incidents(id),
  outcome TEXT NOT NULL DEFAULT 'self_resolved' CHECK (outcome IN ('self_resolved', 'ticket_suggested', 'ticket_created')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bot_triage_logs_user_created
  ON public.bot_triage_logs(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_bot_triage_logs_topic
  ON public.bot_triage_logs(normalized_topic);

ALTER TABLE public.bot_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bot_triage_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bot_incidents_select_policy ON public.bot_incidents;
CREATE POLICY bot_incidents_select_policy
  ON public.bot_incidents
  FOR SELECT
  TO authenticated
  USING (
    status = 'active'
    OR EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND (
          lower(coalesce(p.role, '')) = 'admin'
          OR lower(coalesce(p.role, '')) = 'jefe_mantenimiento'
        )
    )
  );

DROP POLICY IF EXISTS bot_incidents_insert_policy ON public.bot_incidents;
CREATE POLICY bot_incidents_insert_policy
  ON public.bot_incidents
  FOR INSERT
  TO authenticated
  WITH CHECK (
    auth.uid() = created_by
    AND EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND (
          lower(coalesce(p.role, '')) = 'admin'
          OR lower(coalesce(p.role, '')) = 'jefe_mantenimiento'
        )
    )
  );

DROP POLICY IF EXISTS bot_incidents_update_policy ON public.bot_incidents;
CREATE POLICY bot_incidents_update_policy
  ON public.bot_incidents
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND (
          lower(coalesce(p.role, '')) = 'admin'
          OR lower(coalesce(p.role, '')) = 'jefe_mantenimiento'
        )
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND (
          lower(coalesce(p.role, '')) = 'admin'
          OR lower(coalesce(p.role, '')) = 'jefe_mantenimiento'
        )
    )
  );

DROP POLICY IF EXISTS bot_triage_logs_select_policy ON public.bot_triage_logs;
CREATE POLICY bot_triage_logs_select_policy
  ON public.bot_triage_logs
  FOR SELECT
  TO authenticated
  USING (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND (
          lower(coalesce(p.role, '')) = 'admin'
          OR lower(coalesce(p.role, '')) = 'jefe_mantenimiento'
        )
    )
  );

DROP POLICY IF EXISTS bot_triage_logs_insert_policy ON public.bot_triage_logs;
CREATE POLICY bot_triage_logs_insert_policy
  ON public.bot_triage_logs
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

GRANT SELECT, INSERT, UPDATE ON public.bot_incidents TO authenticated;
GRANT SELECT, INSERT ON public.bot_triage_logs TO authenticated;
